### ISSUE TITLE
Work

### ISSUE THREAD

**Issue by ShaykhutdinovTimur** [asm2015coursework/the_best_compilator_ever#3]
Мы будем допиливать? Или всё так и остается???

**Comment by smnikita** [comment]
вряд ли кто-то захочет этим заниматься по фану)

**Comment by Nafanya** [comment]
Perspektivniy proekt, zayavka na uspeshniy startap

**Comment by Nafanya** [comment]
Почему закрыли? Проект мёртв?

**Comment by ShaykhutdinovTimur** [comment]
Да, всё верно.
